/**
 * Reference programs — ids must match server/cascades.js triggerId / unlockId values.
 */
const PROGRAMS = [
  {
    id: 'heap_regular',
    name: {
      en: 'HEAP Regular Benefit',
      es: 'Beneficio Regular HEAP',
    },
    adminAgency: 'OTDA via HRA',
    category: 'Direct payment',
    incomeLimit:
      '60% of State Median Income (varies by household size). Use web_search to verify current thresholds for the 2025-2026 program year.',
    categoricalEligibility:
      'SNAP, Medicaid, SSI, or TANF enrollment grants automatic categorical eligibility — no separate income verification required.',
    estimatedValue:
      '$200–$700/year. Typically $300–$500 for NYC households. Higher amounts for larger households and lower incomes.',
    applicationUrl: 'https://access.nyc.gov/',
    applicationMethod: 'Online via ACCESS HRA or in-person at an HRA HEAP office',
    deadline: 'Typically November through May.',
    requiredDocuments: [
      'Government-issued photo ID',
      'Proof of NYC residency',
      'Proof of income for all household members',
      'Utility account number or heating fuel vendor information',
      'Social Security numbers for all household members',
    ],
    notes:
      'Apply as early in the season as possible — funding is exhausted every year before the window closes.',
    triggers: [],
    triggeredBy: null,
  },

  {
    id: 'heap_emergency',
    name: {
      en: 'HEAP Emergency Benefit',
      es: 'Beneficio de Emergencia HEAP',
    },
    adminAgency: 'OTDA via HRA',
    category: {
      en: 'Emergency',
      es: 'Emergencia',
    },
    incomeLimit: {
      en: 'Same as HEAP Regular. Requires active shutoff notice.',
      es: 'Igual que HEAP Regular. Requiere aviso activo de corte.',
    },
    categoricalEligibility: {
      en: 'Same as HEAP Regular.',
      es: 'Igual que HEAP Regular.',
    },
    estimatedValue: {
      en: 'Up to $600 one-time emergency payment.',
      es: 'Hasta $600 en un pago único de emergencia.',
    },
    applicationUrl: 'https://access.nyc.gov/',
    applicationMethod: 'In-person at an HRA HEAP office (emergency cases receive same-day processing)',
    deadline: 'Available during HEAP Regular window.',
    requiredDocuments: [
      'Active utility shutoff notice or documentation of fuel emergency',
      'All standard HEAP Regular documents',
    ],
    notes: 'Must have active shutoff notice in hand for emergency benefit.',
    triggers: [],
    triggeredBy: null,
  },
  {
    id: 'liheap',
    name: 'LIHEAP / HEAP (application on file)',
    adminAgency: 'OTDA',
    category: 'Direct payment',
    incomeLimit: 'Same as HEAP income limits.',
    categoricalEligibility: 'Used as cascade trigger when a household has an active HEAP/LIHEAP application.',
    estimatedValue: 'Varies — see HEAP Regular or Emergency.',
    applicationUrl: 'https://access.nyc.gov/',
    applicationMethod: 'ACCESS HRA',
    deadline: 'HEAP season.',
    requiredDocuments: [],
    notes: 'Enrollment trigger id for cascade resolution.',
    triggers: [],
    triggeredBy: null,
  },
  {
    id: 'coned_eal',
    name: 'Con Edison Energy Affordability Program (EAL)',
    adminAgency: 'Con Edison',
    category: 'Bill discount',
    incomeLimit: 'Income-based or categorical (SNAP, Medicaid, HEAP).',
    categoricalEligibility: 'HEAP approval, SNAP, or Medicaid enrollment.',
    estimatedValue: 'Up to ~$840/year bill credit (varies).',
    applicationUrl:
      'https://www.coned.com/en/accounts-billing/billing-help/energy-affordability',
    applicationMethod: 'Online or phone',
    deadline: 'Year-round',
    requiredDocuments: ['Proof of enrollment in qualifying program or income documentation'],
    notes: 'Con Edison electric customers only.',
    triggers: [],
    triggeredBy: null,
  },
  {
    id: 'eap_national_grid',
    name: 'National Grid Energy Assistance Program (EAP)',
    adminAgency: 'National Grid',
    category: 'Bill discount',
    incomeLimit: 'Income-based or HEAP categorical.',
    categoricalEligibility: 'HEAP approval qualifies you categorically.',
    estimatedValue: 'Up to ~$720/year (varies).',
    applicationUrl: 'https://www.nationalgridus.com/customer-assistance',
    applicationMethod: 'Phone or service center',
    deadline: 'Year-round',
    requiredDocuments: ['HEAP approval letter or income proof'],
    notes: 'Gas customers in Brooklyn, Queens, Staten Island.',
    triggers: [],
    triggeredBy: null,
  },
  {
    id: 'nyserda_weatherization',
    name: 'Weatherization Assistance Program (WAP) — NYSERDA',
    adminAgency: 'NYSERDA',
    category: 'Weatherization',
    incomeLimit: 'Income-eligible households.',
    categoricalEligibility: 'HEAP approval can prioritize scheduling.',
    estimatedValue: 'Free audits and upgrades — value varies by home.',
    applicationUrl: 'https://www.nyserda.ny.gov/All-Programs/WAP',
    applicationMethod: 'Phone 1-866-697-3732',
    deadline: 'Year-round waitlist',
    requiredDocuments: ['Proof of income', 'Utility bills'],
    notes: 'HEAP can fast-track audit scheduling.',
    triggers: [],
    triggeredBy: null,
  },
  {
    id: 'nyserda_empower',
    name: 'EmPower+ (NYSERDA)',
    adminAgency: 'NYSERDA',
    category: 'Weatherization',
    incomeLimit: 'Income-eligible; SNAP/Medicaid satisfy pre-qualification.',
    categoricalEligibility: 'SNAP or Medicaid enrollment.',
    estimatedValue: 'Typical project value $1,000–$11,000+ depending on measures.',
    applicationUrl: 'https://www.nyserda.ny.gov/All-Programs/EmPower-New-York',
    applicationMethod: 'Online',
    deadline: 'Year-round',
    requiredDocuments: ['SNAP or Medicaid award letter', 'Utility account information'],
    notes: '',
    triggers: [],
    triggeredBy: null,
  },
  {
    id: 'hra_home_energy',
    name: 'HRA Home Energy Supplemental Assistance',
    adminAgency: 'HRA',
    category: 'Direct payment',
    incomeLimit: 'Screened at HEAP approval.',
    categoricalEligibility: 'Automatic screening with HEAP approval through HRA.',
    estimatedValue: 'Up to ~$400 supplemental (varies).',
    applicationUrl: 'https://www.nyc.gov/site/hra/help/energy-assistance.page',
    applicationMethod: 'No separate application — HRA review at HEAP approval',
    deadline: 'HEAP season',
    requiredDocuments: [],
    notes: 'City-funded supplement when eligible.',
    triggers: [],
    triggeredBy: null,
  },
  {
    id: 'solar_for_all',
    name: 'Solar for All (NYSERDA)',
    agency: 'NYSERDA',
    type: 'state',
    adminAgency: 'NYSERDA',
    category: 'Community solar',
    incomeLimit: 'Income-eligible; utility affordability enrollment can expedite.',
    categoricalEligibility: 'EAL or similar programs can satisfy pre-qualification for priority.',
    estimatedValue: 'Up to ~$400/year bill credits (typical community solar)',
    maxBenefitDollars: 400,
    incomeThresholdPct: 80,
    applicationUrl: 'https://www.nyserda.ny.gov/All-Programs/Solar-for-All',
    phone: '1-866-697-3732',
    applicationMethod: 'Online — NYSERDA Solar for All',
    deadline: 'Year-round (waitlist)',
    requiredDocuments: ['Proof of income or qualifying program enrollment', 'Con Edison account number'],
    notes: 'Free community solar subscription for income-eligible households; credit on bill.',
    triggers: [],
    triggeredBy: null,
  },

  // --- Additional programs ---

  {
    id: 'heap_cooling',
    name: { en: 'HEAP Cooling Assistance', es: 'Asistencia de Enfriamiento HEAP' },
    adminAgency: 'OTDA via HRA',
    category: { en: 'Seasonal cooling', es: 'Enfriamiento estacional' },
    incomeLimit: 'Same as HEAP Regular (60% SMI). Priority for seniors 60+, children under 6, disabled members.',
    categoricalEligibility: 'SNAP, Medicaid, SSI, or TANF enrollment grants categorical eligibility.',
    estimatedValue: 'Air conditioner unit (up to ~$800 value) or $200 cooling benefit.',
    applicationUrl: 'https://access.nyc.gov/',
    applicationMethod: 'Online via ACCESS HRA or in-person at HRA HEAP office',
    deadline: 'Available June–August. Apply early — units are limited.',
    requiredDocuments: [
      'Government-issued photo ID',
      'Proof of NYC residency',
      'Proof of income or qualifying program enrollment',
      'Utility account number',
    ],
    notes:
      'Critical for climate justice — heat-related illness disproportionately affects Bronx, Brooklyn, and Queens residents. Seniors and children get priority.',
    triggers: [],
    triggeredBy: 'heap_regular',
  },

  {
    id: 'heap_clean_tune',
    name: { en: 'HEAP Clean & Tune', es: 'HEAP Limpieza y Mantenimiento' },
    adminAgency: 'OTDA via HRA',
    category: 'Heating maintenance',
    incomeLimit: 'Same as HEAP Regular.',
    categoricalEligibility: 'HEAP approval expedites scheduling.',
    estimatedValue: '~$300 equivalent free heating equipment service.',
    applicationUrl: 'https://access.nyc.gov/',
    applicationMethod: 'Through HRA HEAP office',
    deadline: 'HEAP season (fall/winter)',
    requiredDocuments: ['HEAP approval documentation'],
    notes: 'Improves heating efficiency and reduces energy bills long-term.',
    triggers: [],
    triggeredBy: 'heap_regular',
  },

  {
    id: 'heap_herr',
    name: { en: 'HEAP HERR — Heating Equipment Repair/Replacement', es: 'HEAP HERR — Reparación/Reemplazo de Equipo de Calefacción' },
    adminAgency: 'OTDA via HRA',
    category: 'Equipment repair',
    incomeLimit: 'Same as HEAP Regular. Homeowners only.',
    categoricalEligibility: 'HEAP-eligible households can apply.',
    estimatedValue: 'Up to $3,000 in free repair or replacement services.',
    applicationUrl: 'https://access.nyc.gov/',
    applicationMethod: 'Through HRA HEAP office',
    deadline: 'HEAP season',
    requiredDocuments: [
      'Proof of homeownership',
      'HEAP eligibility documentation',
      'Documentation of heating equipment failure',
    ],
    notes: 'Covers furnace, boiler, and heating system repairs for eligible homeowners.',
    triggers: [],
    triggeredBy: null,
  },

  {
    id: 'energyshare',
    name: { en: 'EnergyShare', es: 'EnergyShare' },
    adminAgency: 'Con Edison / HeartShare St. Vincent\'s Services',
    category: 'Emergency grant',
    incomeLimit: 'Income-based, case-by-case review.',
    categoricalEligibility: 'Con Edison customers facing energy hardship.',
    estimatedValue: 'Up to $400 emergency energy grant.',
    applicationUrl: 'https://www.heartshare.org/services/energyshare',
    applicationMethod: 'Apply through HeartShare St. Vincent\'s Services',
    deadline: 'Annual program — apply when facing energy hardship',
    requiredDocuments: [
      'Con Edison account number',
      'Proof of income',
      'Documentation of hardship',
    ],
    notes: 'Emergency grant; Con Edison customers only. Funded by Con Edison customer donations.',
    triggers: [],
    triggeredBy: null,
  },

  {
    id: 'utility_arrears',
    name: { en: 'Utility Arrears Forgiveness', es: 'Perdón de Deuda de Servicios Públicos' },
    adminAgency: 'Con Edison / National Grid',
    category: 'Debt relief',
    incomeLimit: 'Must be enrolled in Con Edison EAL or National Grid EAP.',
    categoricalEligibility: 'EAL or EAP enrollment qualifies for arrears review.',
    estimatedValue: 'Ongoing balance reduction — varies by amount owed.',
    applicationUrl: 'https://www.coned.com/en/accounts-billing/billing-help/payment-assistance',
    applicationMethod: 'Contact utility provider after EAL/EAP enrollment',
    deadline: 'Year-round',
    requiredDocuments: ['EAL/EAP enrollment confirmation', 'Account statement showing arrears'],
    notes: 'Customers enrolled in EAL or EAP may qualify for partial or full forgiveness of past-due balances.',
    triggers: [],
    triggeredBy: 'coned_eal',
  },

  {
    id: 'lifeline',
    name: { en: 'Lifeline Telecom Discount', es: 'Descuento de Telecomunicaciones Lifeline' },
    adminAgency: 'FCC via carrier',
    category: 'Telecom discount',
    incomeLimit: '135% Federal Poverty Level or categorical.',
    categoricalEligibility: 'SNAP, Medicaid, SSI, or TANF enrollment qualifies.',
    estimatedValue: '~$9.25/month (~$111/year) phone or internet discount.',
    applicationUrl: 'https://www.lifelinesupport.org/',
    applicationMethod: 'Apply at lifelinesupport.org or through your phone carrier',
    deadline: 'Year-round',
    requiredDocuments: ['Proof of SNAP/Medicaid/SSI/TANF enrollment or income proof'],
    notes: 'Cross-qualifies with SNAP/Medicaid. Reduces the digital divide for low-income households.',
    triggers: [],
    triggeredBy: null,
  },
];

const PROGRAM_BY_ID = Object.fromEntries(PROGRAMS.map((p) => [p.id, p]));

module.exports = { PROGRAMS, PROGRAM_BY_ID };
