const PROGRAMS = [
  {
    id: 'heap_regular',
    name: 'HEAP Regular Benefit',
    adminAgency: 'OTDA via HRA',
    category: 'Direct payment',
    incomeLimit: '60% of State Median Income (varies by household size). Use web_search to verify current thresholds for the 2025-2026 program year.',
    categoricalEligibility: 'SNAP, Medicaid, SSI, or TANF enrollment grants automatic categorical eligibility — no separate income verification required.',
    estimatedValue: '$200–$700/year. Typically $300–$500 for NYC households. Higher amounts for larger households and lower incomes. Use published HEAP benefit tables.',
    applicationUrl: 'https://access.nyc.gov/',
    applicationMethod: 'Online via ACCESS HRA or in-person at an HRA HEAP office',
    deadline: 'Typically November through May. Use web_search to verify whether the current HEAP window is open.',
    requiredDocuments: [
      'Government-issued photo ID',
      'Proof of NYC residency (lease, utility bill, or bank statement)',
      'Proof of income for all household members (pay stubs, Social Security award letters, tax returns)',
      'Utility account number or heating fuel vendor information',
      'Social Security numbers for all household members',
    ],
    notes: 'Apply as early in the season as possible — funding is exhausted every year before the window closes. SNAP/Medicaid recipients skip income verification.',
    triggers: [],
    triggeredBy: null,
  },
  {
    id: 'heap_emergency',
    name: 'HEAP Emergency Benefit',
    adminAgency: 'OTDA via HRA',
    category: 'Emergency',
    incomeLimit: 'Same income limits as HEAP Regular. Requires an active shutoff notice or imminent fuel runout.',
    categoricalEligibility: 'Same categorical eligibility as HEAP Regular.',
    estimatedValue: 'Up to $600 one-time emergency payment.',
    applicationUrl: 'https://access.nyc.gov/',
    applicationMethod: 'In-person at an HRA HEAP office (emergency cases receive same-day processing)',
    deadline: 'Available during HEAP Regular window. Requires an active emergency — cannot be applied for preemptively.',
    requiredDocuments: [
      'Active utility shutoff notice or documentation of fuel emergency',
      'All standard HEAP Regular documents',
    ],
    notes: 'CRITICAL WARNING: Cannot apply preemptively. Must have active shutoff notice in hand. HRA offers same-day processing for genuine emergencies.',
    triggers: [],
    triggeredBy: null,
  },
];

module.exports = { PROGRAMS };
